package org.poo.entities;

public enum TransactionType {
    SEND_MONEY,
    CREATE_CARD,
    PAY_ONLINE,
    DELETE_ACCOUNT,
    DELETE_CARD,
    ADD_FUNDS,
    ADD_ACCOUNT,
    INSUFFICIENT_FUNDS,
    INSUFFICIENT_FUNDS_FOR_SPLIT,
    DELETE_ONE_TIME,
    CHECK_CARD_STATUS,
    CHANGE_INTEREST_RATE,
    SPLIT,
    ADD_INTEREST,
    WITHDRAW_SAVINGS,
    CASHBACK,
    UPGRADE_PLAN,
    CASHWITHDRAWAL,
    SPLIT_CUSTOM,
    INSUFFICIENT_FUNDS_FOR_SPLIT_CUSTOM,
    SPENDING,
    DEPOSIT,
    UPGRADE_PLAN_NO_FUNDS

}
